# Site settings
title: chgallen.com
email: chad@chgallen.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of Chad H.G. Allen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chgallen.com" # the base hostname & protocol for your site
twitter_username: chgallen
github_username:  chgallen

# Build settings
markdown: kramdown
