# Site settings
title: C.H.G. Allen
email: chad@chgallen.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of C. H. G. Allen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chgallen
github_username:  chgallen

# Build settings
markdown: kramdown
